chat:
  broker: rabbit
  kafka-topic: messages
  rabbitmq-queue: messages

jwt:
  expirationMs: 604800000
  refreshExpirationMs: 604800000
  secret: heartcookingSecretKey

management:
  info:
    git:
      mode: full

server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: somePassword

  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: heartcooking
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  liquibase:
    change-log: classpath:/db/changelog/dbchangelog.xml
    default-schema: heartcooking

  profiles:
    active: dev

  redis:
    host: localhost
    port: 6379
    timeout: 60000
    time-to-live: 60000
    password: